---

- name: Install krusader file manager
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - krusader 
    ansible_connection: ssh
    ansible_host: "{{ args_file_ipaddress }}"
  become: true

- name: Install Dolphin
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - dolphin 
    ansible_connection: ssh
    ansible_host: "{{ args_file_ipaddress }}"
  become: true

- name: Install Thunar
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - thunar
    ansible_connection: ssh
    ansible_host: "{{ args_file_ipaddress }}"
  become: true



