---


- name: Install cinnamon
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  when: 'prop_desktop == "cinnamon"'
  vars:
    packages:
    - task-cinnamon-desktop 
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Install xfce
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  when: 'prop_desktop == "xfce"'
  vars:
    packages:
    - task-xfce-desktop 
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Install gnome
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  when: 'prop_desktop == "gnome"'
  vars:
    packages:
    - gnome-core 
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

