---

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/repos/edge stable main
    state: present
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Install Microsoft Edge
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  when: 'prop_desktopprop_arch == "x64"'
  vars:
    packages:
    - microsoft-edge-stable 
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

