---

- name: Install Kitty Terminal
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - kitty 
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

# TODO Add config file for Kitty



- name: Install Alactritty Terminal
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - alacritty 
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true


# TODO Add config file for alacritty



- name: Install Terminator Terminal
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - terminator 
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true


# TODO Add config file for terminator


# TODO Test TABBY


