---

- name: "Playbook: Config HW"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.linuxdesk.installdesktop
      vars:
        args_desk_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.linuxdesk.kde
      vars:
        args_kde_ipaddress: "{{ prop_ipaddress }}"
        args_kde_username: "{{ prop_admin_username }}"
        args_kde_groupname: "{{ prop_admin_groupname }}"
      when: 'prop_desktop == "kde"'

    - ansible.builtin.include_role:
        name: alex.ms.desktop
      vars:
        args_desktop_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.linuxdesk.installremotedesktop
      vars:
        args_remote_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.linuxdesk.installbrowser
      vars:
        args_browser_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.linuxdesk.installterminal
      vars:
        args_terminal_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.linuxdesk.installfilemanager
      vars:
        args_file_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.linuxdesk.installtexteditor
      vars:
        args_text_ipaddress: "{{ prop_ipaddress }}"
